### ISSUE TITLE
Dependencies are including comment lines from requirements.txt files

### ISSUE THREAD

**Issue by nschonni** [canada-ca/ore-ero#1232]
EX:
```yaml
- dependency: # This file is autogenerated. Do not edit it manually.
  origin: pypi
  type: core
  admins: 
    - tbs-sct
  projects: 
    - projectName: 
        en: Notify
        fr: Notification
- dependency: # Run `make freeze-requirements` to update requirements.txt
  origin: pypi
  type: core
  admins: 
    - tbs-sct
  projects: 
    - projectName: 
        en: Notify
        fr: Notification
- dependency: # with package version changes made in requirements-app.txt
  origin: pypi
  type: core
  admins: 
    - tbs-sct
  projects: 
    - projectName: 
        en: Notify
        fr: Notification
```
