### ISSUE TITLE
Changes to project are not committed to file in PR

### ISSUE THREAD

**Issue by WJXHenry** [canada-ca/ore-ero#255]
The `merge` function of the `YamlWriter` class in [*this*](https://github.com/canada-ca/ore-ero/blob/bdccdd7754b3205b346c33653659d9efa619641c/assets/js/src/git-file-manager.js#L73-L110) file does not seem to be updating existing content.

When the user selects an existing project and changes a field value (in my case, I changed the English description), the file that gets committed does not seem to contain the change.

Note [this PR](https://github.com/canada-ca/ore-ero/pull/254#issue-283455349).

Expected description to be:
```yaml
description:
    en: 'The English description should change'
    fr: 'YouCanBenefit est une application Web qui augmente la découvrabilité des programmes d''avantages sociaux pour les personnes moins fortunées et leurs alliés.'
```

Instead (no change):
https://github.com/canada-ca/ore-ero/blob/297d2bc7e66efdda63ca061e54dc8aced5c657d3/_data/code/municipal/edmonton_ab.yml#L13-L15
